### ISSUE TITLE
cannot convert from 'initializer list' to 'dx::RootBindings<1>

### ISSUE THREAD

**Issue by ThoBre** [Ohjurot/DX12-YT#1]
https://github.com/Ohjurot/DX12-YT/blob/b71683843716efcfd9ff4c9c8b4d0a9fa14b1af6/src/engine/ui/UIRenderState.cpp#L93

**Comment by Ohjurot** [comment]
Please try out to clone and compile the code on any of the stable tags like https://github.com/Ohjurot/DX12-YT/tree/VV.3 

The current main branch is not guaranteed to work since it is a bit ahead of the last video.

**Comment by Ohjurot** [comment]
I have updated this file: https://github.com/Ohjurot/DX12-YT/blob/main/src/dx/descriptors/RootBindings.h (Copy the current version into your projecte and it will work). However the development version from github ("main") will not work by design!
